# Generated by Django 4.0.4 on 2022-04-18 02:23

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('age', models.PositiveSmallIntegerField()),
                ('username', models.CharField(default='', max_length=128, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('email', models.CharField(default='', max_length=128)),
                ('phone', models.CharField(default='', max_length=10)),
                ('provider', models.CharField(default='', max_length=128)),
                ('mri', models.CharField(default='', max_length=128)),
                ('aki', models.CharField(default='', max_length=128)),
                ('exchange', models.CharField(default='', max_length=128)),
                ('location', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
    ]
