# Generated by Django 4.0.4 on 2022-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='location',
        ),
    ]
